package com.alaa.school.domain;

public enum ClassType {
    FIRSTGRADE,SECONGRADE,THIRDGRADE,FOURTHGRADE,FIFTHGRADE,
    SITHGRADE,SEVENGRADE,EIGTHGRADE,NINETHGRADE,TENTHGRADE,
    ELEVENTHGRADE,TWEHFTHGRADE
}

